### ISSUE TITLE
Remove loading custom JavaScript for session context and reading cookies

### ISSUE THREAD

**Issue by matus-tomlein** [snowplow-incubator/snowplow-flutter-tracker#13]
When upgrading Flutter to version 3, the tracker throws errors on Web that the `isSnowplowInstalled` function can not be found. The problem was reporting in [this Discourse post](https://discourse.snowplowanalytics.com/t/flutter-web-tracker-does-not-load-with-flutter-3-x/6970/2).

**Comment by atrope** [comment]
Hi @matus-tomlein More than 2 months broken.. will you guys be able to fix it?

**Comment by matus-tomlein** [comment]
Sorry for the delay @atrope. This is on our list but unfortunately a new Flutter release hasn't made it into our priorities for Q3. We still plan to fix this as soon as time permits. We also welcome external contributions if you'd like to take on the fix.
