### ISSUE TITLE
Android: 'kotlin-android-extensions' plugin is deprecated

### ISSUE THREAD

**Issue by jeremie-movify** [snowplow-incubator/snowplow-flutter-tracker#35]
Good morning,

We have a couple Flutter apps (currently in the stores) which depend on `snowplow_tracker`.
The latest version (`0.3.0`) of `snowplow_tracker` has an Android dependency to the `kotlin-android-extensions` plugin, which is deprecated:
https://developer.android.com/topic/libraries/view-binding/migration

I've forked this repository and pushed changes in a branch from which a Pull Request could be opened:
https://github.com/jeremie-movify/snowplow-flutter-tracker/commit/c9e686618ced4119a6cc94e97a313a74ca1c9867#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a

The removal of the said plugin doesn't remove any existing functionality. Instead, it allows us to use the latest version of Flutter (3.10).

Cheers!

**Comment by erickok** [comment]
We would also like the see this change.

**Comment by matus-tomlein** [comment]
Thanks for reporting this issue! We have just published the version 0.4.0 of the tracker which fixes this.
